#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail; shopt -s nullglob

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

function build() {
    echo "🎹 building..."
    flutter build web --web-renderer html --release &> /dev/null
}

function compress() {
    echo "🍔 compressing..."
    cd build/web/
    npx lzutf8-file -c main.dart.js main.dart.js.compressed
    cd "$SCRIPT_DIR"
}

function dev() {
    echo "🚀 developing..."
    echo ""
    cd build/web/
    npx http-server -c-1
    cd "$SCRIPT_DIR"
}

function clean() {
    echo "🛁 cleaning..."
    rm -rf build/web
}

function ci() {
    clean
    build
    compress
    dev
}

function help() {
    echo "available commands: build, compress, dev, clean, help"
}

[[ -z "${1-}" ]] && help && exit 0

case $1 in
	build|compress|dev|clean|ci) "$1" "${@:2}" ;;
	*) help ;;
esac
